import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


/**
 *
 * @author Asus
 */
public class Vote extends javax.swing.JFrame {

    public int person1 = 0, person2 = 0, person3 = 0;

    /**
     * Creates new form Vote
     * @throws java.io.FileNotFoundException
     */
    public Vote() throws FileNotFoundException, IOException {
        initComponents();
        initialize();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rdbGrp = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Submit = new javax.swing.JButton();
        Signout = new javax.swing.JButton();
        rdb_1 = new javax.swing.JRadioButton();
        rdb_2 = new javax.swing.JRadioButton();
        rdb_3 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 102, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Welcome! Please give your vote.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jLabel1)
                .addContainerGap(211, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));

        Submit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Submit.setText("Submit vote");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });

        Signout.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Signout.setText("Sign Out");
        Signout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignoutMouseClicked(evt);
            }
        });
        Signout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignoutActionPerformed(evt);
            }
        });

        rdbGrp.add(rdb_1);
        rdb_1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rdb_1.setText("Person 1");

        rdbGrp.add(rdb_2);
        rdb_2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rdb_2.setText("Person 2");

        rdbGrp.add(rdb_3);
        rdb_3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rdb_3.setText("Person 3");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Signout, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 259, Short.MAX_VALUE)
                        .addComponent(Submit, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(rdb_1, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                            .addComponent(rdb_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rdb_3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(rdb_1)
                .addGap(27, 27, 27)
                .addComponent(rdb_2)
                .addGap(30, 30, 30)
                .addComponent(rdb_3)
                .addGap(72, 72, 72)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Submit, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Signout, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(134, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SignoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignoutActionPerformed

    }//GEN-LAST:event_SignoutActionPerformed

    private void SignoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignoutMouseClicked
        VoterLogin lgf = new VoterLogin();
        lgf.setVisible(true);
        lgf.pack();
        lgf.setLocationRelativeTo(null);
        lgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_SignoutMouseClicked

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        ButtonGroup b = new ButtonGroup();
        b.add(rdb_1);
        b.add(rdb_2);
        b.add(rdb_3);
        if (rdb_1.isSelected()) {
            person1 = person1 + 1;
            BufferedWriter p1;
            try {
                p1 = new BufferedWriter(new FileWriter("person1.txt"));
                p1.write(String.valueOf(person1));
                p1.close();
            } catch (IOException ex) {
                Logger.getLogger(Vote.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else if (rdb_2.isSelected()) {
            person2 = person2 + 1;

            BufferedWriter p2;
            try {
                p2 = new BufferedWriter(new FileWriter("person2.txt"));
                p2.write(String.valueOf(person2));
                p2.close();
            } catch (IOException ex) {
                Logger.getLogger(Vote.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else if (rdb_3.isSelected()) {
            person3 = person3 + 1;
            BufferedWriter p3;
            try {
                p3 = new BufferedWriter(new FileWriter("person3.txt"));
                p3.write(String.valueOf(person3));
                p3.close();
            } catch (IOException ex) {
                Logger.getLogger(Vote.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
        JOptionPane.showMessageDialog(null, "Thank you so much!");
        new VoterLogin().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_SubmitActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new Vote().setVisible(true);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Vote.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Vote.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Signout;
    private javax.swing.JButton Submit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.ButtonGroup rdbGrp;
    private javax.swing.JRadioButton rdb_1;
    private javax.swing.JRadioButton rdb_2;
    private javax.swing.JRadioButton rdb_3;
    // End of variables declaration//GEN-END:variables

    /*private void initialize() throws FileNotFoundException, IOException {
     BufferedReader r1 = new BufferedReader(new FileReader("C:\\Users\\Asus\\Documents\\MY java projects\\VotingManagementSystem\\person1.txt"));
     BufferedReader r2 = new BufferedReader(new FileReader("C:\\Users\\Asus\\Documents\\MY java projects\\VotingManagementSystem\\person2.txt"));
     BufferedReader r3 = new BufferedReader(new FileReader("C:\\Users\\Asus\\Documents\\MY java projects\\VotingManagementSystem\\person3.txt"));
        
     int x;
     person1=r1.read();
     person2=r2.read();
     person3=r2.read();
     }*/
    private void initialize() throws FileNotFoundException, IOException {
        BufferedReader r1 = new BufferedReader(new FileReader("C:\\Users\\Asus\\Documents\\MY java projects\\VotingManagementSystem\\person1.txt"));
        BufferedReader r2 = new BufferedReader(new FileReader("C:\\Users\\Asus\\Documents\\MY java projects\\VotingManagementSystem\\person2.txt"));
        BufferedReader r3 = new BufferedReader(new FileReader("C:\\Users\\Asus\\Documents\\MY java projects\\VotingManagementSystem\\person3.txt"));
        String s;
        if ((s = r1.readLine()) == null) {
            person1 = 0;
        } else {
            person1 = Integer.parseInt(s);

        }

        if ((s = r2.readLine()) == null) {
            person2 = 0;
        } else {
            person2 = Integer.parseInt(s);

        }

        if ((s = r3.readLine()) == null) {
            person3 = 0;
        } else {
            person3 = Integer.parseInt(s);

        }

        r1.close();
        r2.close();
        r3.close();
    }
}
